### ISSUE TITLE
Vue3 - type props warning

### ISSUE THREAD

**Issue by zertex** [KingSora/OverlayScrollbars#551]
I have got
`[Vue warn]: Invalid prop: type check failed for prop "options". Expected Boolean | Null, got Object  
  at <OverlayScrollbarsComponent ...`

on template:
```
<OverlayScrollbarsComponent
      class="os-vue"
      ref="osRef"
      :options="{
          scrollbars: {
            theme: 'os-theme-light',
            autoHide: props.autoHide
          },
        }"
      defer
  >
  <slot></slot>
  </OverlayScrollbarsComponent>
```

why?

**Comment by KingSora** [comment]
@zertex Good day :) 

What version of `overlayscrollbars-vue` are you using?

**Comment by zertex** [comment]
0.5.3

**Comment by KingSora** [comment]
@zertex I might have messed up the typings for `0.5.3`. Can you try whether this works:

```
<OverlayScrollbarsComponent
      class="os-vue"
      ref="osRef"
      :options="{
          scrollbars: {
            theme: 'os-theme-light',
            autoHide: props.autoHide
          },
        }"
      :events="{}"
      defer
  >
  <slot></slot>
  </OverlayScrollbarsComponent>
```

**Comment by KingSora** [comment]
That seems weird to me. I'm not getting this issue at all event with a completely fresh vue3 project. Are you using `vue2` or `vue3`?

**Comment by zertex** [comment]
```
"peerDependencies": {
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vicons/material": "^0.12.0",
    "@vitejs/plugin-vue": "^4.2.3",
    "sass": "^1.32.12",
    "sass-loader": "^12.0.0",
    "vite": "^4.4.5",
    "vite-plugin-dts": "^3.5.2",
    "vue": "^3.3.4"
  },
  "dependencies": {
    "overlayscrollbars-vue": "^0.5.3",
    "vite-plugin-fonts": "^0.7.0",
    "vue-router": "^4.2.4"
  }
```

**Comment by KingSora** [comment]
@zertex please install the `overlayscrollbars` package, its a peer dependency of `overlayscrollbars-vue`

**Comment by zertex** [comment]
unfortunately the warnings remain

**Comment by KingSora** [comment]
@zertex Are you able to provide an example repo or some sort of example so I can see whats going on?

**Comment by zertex** [comment]
I'll make an example

**Comment by KingSora** [comment]
@zertex I've now published `overlayscrollbars-vue` version `0.5.4` which fixed typing issues with optional props. While developing it I noticed that sometimes the VSCode extension for vue sometimes doesn't reflect the latest state of the project. What helped was restarting the IDE or the language server.

**Comment by zertex** [comment]
Unfortunately, the warning remains. i'll try to do an example in the sandbox tomorrow

**Comment by stixbunny** [comment]
I've come across this same issue, restarting Volar as well as VSCode sadly didn't work.
I'm working with:

"overlayscrollbars": "^2.3.0",
"overlayscrollbars-vue": "^0.5.4",
"vue": "^3.3.4",

**Comment by KingSora** [comment]
@stixbunny Thanks for the example! :) 

In your case the error is correct, because your options aren't correct. If you change your options to:
```
{
  paddingAbsolute: true,
  showNativeOverlaidScrollbars: true,
  scrollbars: {
    theme: 'os-theme-dark',
    clickScroll: true,
    autoHide: 'scroll',
  },
}
```

Which is the equivalent of the `v1` options your specified, it should be working.

**Comment by KingSora** [comment]
@zertex which Vue plugin are using in your IDE?

**Comment by stixbunny** [comment]
@KingSora I tried but still no luck :(. Although thank you for pointing me in the right direction.

It should be noted I do get a warning on the option prop assignment:
![overlayscrollbars](https://github.com/KingSora/OverlayScrollbars/assets/1787168/4a9f8173-93bc-4928-a96e-f5f7d5674e92)

That gets fixed if I type options as:
```
import type { PartialOptions } from "overlayscrollbars";
const options : PartialOptions = {
  paddingAbsolute: true,
  showNativeOverlaidScrollbars: true,
  scrollbars: {
    theme: 'os-theme-dark',
    clickScroll: true,
    autoHide: 'scroll',
  },
};
```
But I still get the same warning:
![image](https://github.com/KingSora/OverlayScrollbars/assets/1787168/71bcf6cf-3999-45f1-9e70-9f500aec6128)

If it's worth anything, I'm running Volar with takeover mode with:

- TypeScript Vue Plugin (Volar)  v1.8.8
- Vue Language Features (Volar)  v1.8.8

**Comment by zertex** [comment]
@KingSora, still no luck too :(

> @zertex which Vue plugin are using in your IDE?

PhpStorm with
https://plugins.jetbrains.com/plugin/9442-vue-js

**Comment by KingSora** [comment]
This seems to be a problem with how vue3 handles its `type-based declaration` for props. (https://vuejs.org/guide/typescript/composition-api.html#typing-component-props) It looks like its inferring the runtime props incorrectly in my case.

So I've reverted back to `runtime declaration` to resolve this issue. Please try out `overlayscrollbars-vue` version `0.5.5` and report back your results.

**Comment by stixbunny** [comment]
I no longer get any warnings. Seems resolved on my end. Thanks a bunch!

**Comment by KingSora** [comment]
@zertex is the issue also fixed for you?

**Comment by meteyou** [comment]
@KingSora i had the same issue with `overlayscrollbars-vue` and `0.5.3`. an update to `0.5.5` fixed also my issue. Thx for your work!

**Comment by KingSora** [comment]
Nice! I'll close this issue now. @zertex in case this issue isn't resolved for you please don't hesitate to create a new one

**Comment by zertex** [comment]
> @zertex is the issue also fixed for you?

Thanks!
