### ISSUE TITLE
Weird double render with SolidJS when certain control components are used like `<Show />`

### ISSUE THREAD

**Issue by ryanzec** [KingSora/OverlayScrollbars#700]
**Describe the bug**
Is seems like when control components are used inside of the overlay scrollbars component, I can get a weird double render effect when a signal updates related to the control component. In the linked example, I just used a `<Show />` for simplicity but I have noticed this with `<For />` too.

**To Reproduce**

1. Go to https://stackblitz.com/edit/overlayscrollbars-solid-iavjenex?file=package.json,src%2FApp.tsx
2. Open up the console
3. ERROR: You will see 2 render console logs but should only have one (the initial render should have the signal as false to not render the content)
4. Comment out the scrollbars component
5. Reload the preview
6. You will see 1 render console log as expected

You also only get one render log if you comment out the `<Show />` but I should be able to use the `<Show />` inside the scrollbars without double renders. 

**Expected behavior**
Things in the scrollbars component not not re-render unnecessarily. 

**Examples**
https://stackblitz.com/edit/overlayscrollbars-solid-iavjenex?file=package.json,src%2FApp.tsx

**Environment**
- OverlayScrollbars version: Latest
- Used Operating System(s): Mac OS X 12
- Used Browser(s) (with version): Chrome (Latest)
- SolidJS: 1.9.3 (Latest)

**Additional context**
Not sure if I am doing something wrong with SolidJS here but I think the SolidJS code is good.

**Comment by ryanzec** [comment]
@KingSora So it seems like a work around to this issue is either making sure the first element that is wrapped by overlay scrollbars does not use a signal or pull the content into a variable. Lucky just pulling it into a variable work in my use case as shown here:
https://stackblitz.com/edit/overlayscrollbars-solid-tj2sz1vz?file=src%2FApp.tsx

However it seems like something that could be fixed in the library itself. The SolidJS discord help me with this here with a possible direction to solve this in the library itself I think here: https://discordapp.com/channels/722131463138705510/722131463889223772/1325350338508882052

**Comment by KingSora** [comment]
@ryanzec Thanks for the report! I've published `overlayscrollbars-solid v0.5.6` where I've implemented the suggested fix! :)

**Comment by KingSora** [comment]
@ryanzec I'm closing the issue for now, In case I've missed something and the issue still persists feel free to re-open the issue :)

**Comment by ryanzec** [comment]
@KingSora Sorry for the delay, I am still seeing the issue with I don't manually use the `children()` helper. 
Maybe something in my code is causing this issue too however I just don't have the time to debug this further right now but here is that context on how I am using the `OverlayScrollbarsComponent` (I have this component as an abstraction):
```tsx
const ScrollArea = (passedProps: OverlayScrollbarsComponentProps) => {
  const [props] = splitProps(passedProps, ['options', 'class', 'children']);
  const options = props.options || {};

  // @todo(refactor) this is to work around a bug in OverlayScrollbars that cause a double render of content
  // @todo(refactor) depending if the top element wrapped uses a signal
  // @todo(refactor) reference: https://github.com/KingSora/OverlayScrollbars/issues/700
  const contentAsVariable = children(() => props.children);

  return (
    <OverlayScrollbarsComponent
      defer
      class={classnames(styles.scrollArea, props.class)}
      options={{
        ...props.options,
        scrollbars: {
          ...options.scrollbars,
          ...defaultScrollbarOptions.scrollbars,
        },
      }}
    >
      {contentAsVariable()}
    </OverlayScrollbarsComponent>
  );
};
```
If I get rid of `const contentAsVariable = children(() => props.children);` and just pass `props.children`the double render happen in my code.

**Comment by KingSora** [comment]
@ryanzec Are you sure you're using the correct version of the package `overlayscrollbars-solid`? I can't reproduce the bug anymore on stackblitz, neither with your `ScrollArea` nor with the original  `OverlayScrollbars` component.

**Comment by ryanzec** [comment]
@KingSora I did verify I am using the latest versions of the core and solid overlay scrollers libraries.
